version: '3'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_local
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CLIENT_USERS=root
      - KAFKA_CLIENT_PASSWORDS=secret
    ports:
      - '19092:9092'
    networks:
      - kafka_network
  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui_local
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - '18082:8080'
    restart: unless-stopped
    networks:
      - kafka_network
    depends_on:
      - kafka

networks:
  kafka_network:
    external: true
